const bookData = {
    // --- Oude Testament (otBooks) ---
    'Genesis': { summary: 'Het begin van de schepping, de zondeval en de aartsvaders.', people: 'Adam, Eva, Noach, Abraham' },
    'Exodus': { summary: 'De uittocht uit Egypte en de wetgeving bij de Sinai.', people: 'Mozes, Aäron, Farao' },
    'Leviticus': { summary: 'Wetten rondom heiligheid, offers, priesterschap en reinheid.', people: 'Mozes, Aäron, Nadab, Abihu' },
    'Numeri': { summary: 'Volkstellingen en de veertigjarige woestijnreis naar het beloofde land.', people: 'Mozes, Jozua, Kaleb, Bileam' },
    'Deuteronomium': { summary: 'Herhaling en toelichting van de wet vlak voor de intocht in Kanaän.', people: 'Mozes, Jozua' },
    'Jozua': { summary: 'De verovering en verdeling van het beloofde land Kanaän.', people: 'Jozua, Rachab, Achan' },
    'Rechters': { summary: 'Een cyclus van afval, onderdrukking en bevrijding door leiders (rechters).', people: 'Debora, Gideon, Simson' },
    'Ruth': { summary: 'Een verhaal over trouw, liefde en verlossing tijdens de richterentijd.', people: 'Ruth, Naomi, Boaz' },
    '1 Samuel': { summary: 'De overgang van richters naar de monarchie en de opkomst van David.', people: 'Samuel, Saul, David, Jonatan' },
    '2 Samuel': { summary: 'Het koningschap van David, zijn triomfen en zijn beproevingen.', people: 'David, Batseba, Natan, Absalom' },
    '1 Koningen': { summary: 'Het koningschap van Salomo, de bouw van de tempel en de scheuring van het rijk.', people: 'Salomo, Jerobeam, Rehabeam, Elia' },
    '2 Koningen': { summary: 'De geschiedenis van de verdeelde koninkrijken tot aan de ballingschap.', people: 'Elisa, Hizkia, Josia, Nebukadnezar' },
    '1 Kronieken': { summary: 'Geslachtsregisters en een priesterlijk perspectief op de regering van David.', people: 'Adam, David, Salomo' },
    '2 Kronieken': { summary: 'De heerschappij van Salomo en de geschiedenis van het koninkrijk Juda.', people: 'Salomo, Josafat, Hizkia, Josia' },
    'Ezra': { summary: 'De terugkeer van de Joodse ballingen en de wederopbouw van de tempel.', people: 'Ezra, Zerubbabel, Kores' },
    'Nehemia': { summary: 'De herbouw van de muren van Jeruzalem en geestelijke hervormingen.', people: 'Nehemia, Ezra, Sanballat' },
    'Ester': { summary: 'De redding van het Joodse volk in het Perzische Rijk van vernietiging.', people: 'Ester, Mordechai, Haman, Ahasveros' },
    'Job': { summary: 'Een diepzinnige dialoog over het lijden van de rechtvaardige en Gods soevereiniteit.', people: 'Job, Elifaz, Bildad, Zofar, Elihu' },
    'Psalmen': { summary: 'Liederen, gebeden en gedichten over lofprijs, boete, verdriet en vertrouwen.', people: 'David, Asaf, de zonen van Korach' },
    'Spreuken': { summary: 'Praktische levenswijsheden en ethische lessen gebaseerd op het ontzag voor God.', people: 'Salomo, Agur, Lemuel' },
    'Prediker': { summary: 'Filosofische reflectie over de vergankelijkheid van het leven en de zin ervan.', people: 'De Prediker (Salomo)' },
    'Hooglied': { summary: 'Een poëtische viering van liefde, huwelijk en verlangen.', people: 'De bruidegom (Salomo), de Sulammitische' },
    'Jesaja': { summary: 'Profetieën over oordeel, troost en de komst van de Lijdende Dienstknecht (de Messias).', people: 'Jesaja, koning Achaz, koning Hizkia' },
    'Jeremia': { summary: 'Oproepen tot bekering vóór de val van Jeruzalem en de belofte van een nieuw verbond.', people: 'Jeremia, Baruch, koning Sedekia' },
    'Klaagliederen': { summary: 'Rouwdichten over de verwoesting van Jeruzalem en de ballingschap.', people: 'Jeremia' },
    'Ezechiël': { summary: 'Visioenen van Gods glorie, het oordeel en het toekomstige herstel van Israël.', people: 'Ezechiël' },
    'Daniël': { summary: 'Verhalen over trouw in ballingschap en apocalyptische visioenen over wereldrijken.', people: 'Daniël, Sadrach, Mesach, Abednego, Nebukadnezar' },
    'Hosea': { summary: 'Gods onvoorwaardelijke trouw aan een ontrouw volk, gesymboliseerd door een huwelijk.', people: 'Hosea, Gomer' },
    'Joël': { summary: 'De sprinkhanenplaag als voorafspiegeling van de Dag van de Heer en de uitstorting van de Geest.', people: 'Joël' },
    'Amos': { summary: 'Aanklacht tegen sociale onrechtvaardigheid en schijnvroomheid in het noordelijke rijk.', people: 'Amos, Amazja' },
    'Obadja': { summary: 'Een profetie over het oordeel over Edom wegens vijandigheid tegenover Israël.', people: 'Obadja' },
    'Jona': { summary: 'Een profeet die vlucht voor Gods opdracht en Gods genade voor Nineve.', people: 'Jona' },
    'Micha': { summary: 'Oordeel over onrecht en de belofte van een heerser die uit Betlehem zal komen.', people: 'Micha' },
    'Nahum': { summary: 'Aankondiging van de val en het definitieve oordeel over Nineve.', people: 'Nahum' },
    'Habakuk': { summary: 'Vragen en geworstel over Gods rechtvaardigheid, eindigend in vertrouwen.', people: 'Habakuk' },
    'Sefanja': { summary: 'Aankondiging van de Dag van de Heer en de belofte van herstel voor een restvolk.', people: 'Sefanja, koning Josia' },
    'Haggai': { summary: 'Aansporing aan de teruggekeerde ballingen om de tempel af te bouwen.', people: 'Haggai, Zerubbabel, Jozua de hogepriester' },
    'Zacharia': { summary: 'Profetische visioenen over de wederopbouw, de Messias en Gods uiteindelijke koninkrijk.', people: 'Zacharia, Zerubbabel, Jozua' },
    'Maleachi': { summary: 'Vermaningen over lauwheid in het geloof en de belofte van de voorloper van de Messias.', people: 'Maleachi' },

    // --- Nieuwe Testament (ntBooks) ---
    'Matteüs': { summary: 'Het leven van Jezus, geschreven voor een Joods publiek.', people: 'Jezus, de discipelen, Maria' },
    'Marcus': { summary: 'Een beknopt en dynamisch verslag van het handelen en lijden van Jezus als Dienaar.', people: 'Jezus, Petrus, Johannes de Doper' },
    'Lucas': { summary: 'Een gedetailleerd historisch evangelie over Jezus als de Verlosser van alle mensen.', people: 'Jezus, Lucas, Maria, Zacharias, Elisabet' },
    'Johannes': { summary: 'Theologisch evangelie dat focust op Jezus als de eeuwige Zoon van God.', people: 'Jezus, Johannes, Nicodemus, Lazarus' },
    'Handelingen': { summary: 'De uitstorting van de Heilige Geest en de verspreiding van het evangelie en de vroege kerk.', people: 'Petrus, Paulus, Stefanus, Barnabas' },
    'Romeinen': { summary: 'Grondige uiteenzetting van redding door genade en geloof in Christus.', people: 'Paulus' },
    '1 Korintiërs': { summary: 'Praktische richtlijnen voor verdeeldheid, moraal, gaven van de Geest en de opstanding.', people: 'Paulus, Apollos' },
    '2 Korintiërs': { summary: 'Verdediging van Paulus’ apostelschap en troost in beproevingen.', people: 'Paulus, Titus' },
    'Galaten': { summary: 'Verdediging van de christelijke vrijheid en rechtvaardiging door geloof in plaats van wet.', people: 'Paulus, Petrus' },
    'Efeziers': { summary: 'De rijkdom van Gods genade, de eenheid van de kerk en de geestelijke wapenrusting.', people: 'Paulus, Tychikus' },
    'Filippenzen': { summary: 'Een brief vol vreugde, bemoediging en eensgezindheid ondanks gevangenschap.', people: 'Paulus, Timoteüs, Epafroditus' },
    'Kolossenzen': { summary: 'De absolute suprematie en toereikendheid van Christus boven menselijke tradities.', people: 'Paulus, Epafras' },
    '1 Tessalonicenzen': { summary: 'Bemoediging van een jonge gemeente en onderwijs over de wederkomst van Jezus.', people: 'Paulus, Silas, Timoteüs' },
    '2 Tessalonicenzen': { summary: 'Correctie van misvattingen rondom de Dag van de Heer en de opstandigheid.', people: 'Paulus, Silas' },
    '1 Timoteüs': { summary: 'Instructies voor leiderschap, kerkorde en gezonde leer in de plaatselijke gemeente.', people: 'Paulus, Timoteüs' },
    '2 Timoteüs': { summary: 'Paulus’ laatste afscheidsbrief met aansporingen om vol te houden in het geloof.', people: 'Paulus, Timoteüs, Lukas' },
    'Titus': { summary: 'Instructies over het aanstellen van oudsten en het leiden van een vroom leven op Kreta.', people: 'Paulus, Titus' },
    'Filemon': { summary: 'Een persoonlijk pleidooi om de weggelopen slaaf Onesimus als broeder te ontvangen.', people: 'Paulus, Filemon, Onesimus' },
    'Hebreeën': { summary: 'Aantoonbaar bewijs dat Jezus en het nieuwe verbond superieur zijn aan de wet en offers.', people: 'De auteur, Melchisedek, Jozua, Mozes' },
    'Jakobus': { summary: 'Praktische instructies dat waar geloof zichtbaar moet worden door goede daden.', people: 'Jakobus' },
    '1 Petrus': { summary: 'Bemoediging en hoop voor christenen die lijden onder vervolging.', people: 'Petrus, Silvanus' },
    '2 Petrus': { summary: 'Waarschuwing tegen dwaalleraars en aansporing tot standvastigheid in de eindtijd.', people: 'Petrus' },
    '1 Johannes': { summary: 'Oproep tot wandel in het licht, liefde voor elkaar en zekerheid van het eeuwige leven.', people: 'Johannes' },
    '2 Johannes': { summary: 'Korte brief over het bewaren van waarheid en liefde tegen misleiders.', people: 'Johannes (de oudste), de uitverkoren vrouw' },
    '3 Johannes': { summary: 'Lof voor gastvrijheid en waarschuwing tegen machtswellust in de gemeente.', people: 'Johannes, Gajus, Diotrefes, Demetrius' },
    'Judas': { summary: 'Aansporing om krachtig te strijden voor het geloof tegen binnengedrongen dwaalleraars.', people: 'Judas' },
    'Openbaring van Jezus': { summary: 'Visioenen over de eindtijd en de nieuwe wereld.', people: 'Johannes, Het Lam' }
};